#!/bin/bash
# Get directory of this script into DIR
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CORRECT="https://masseria.org/"
URL=`curl -s http://masseria.org -w"%{redirect_url}"`

if [ "$URL" = "$CORRECT" ]; then
    echo "Internet OK"
else
    echo "Internet NOT OK received URL="$URL",expected="$CORRECT
    $DIR/post-connect.py
fi
